#!/usr/bin/env bash
# Summary: Explain how the current nvim version is set
set -e
[ -n "$NVIMENV_DEBUG" ] && set -x

if [ -n "$NVIMENV_VERSION" ]; then
  echo "NVIMENV_VERSION environment variable"
else
  nvimenv-version-file
fi
