#!/usr/bin/env bash
# Summary: Detect the file that sets the current nvimenv version
set -e
[ -n "$NVIMENV_DEBUG" ] && set -x

find_local_version_file() {
  local root="$1"
  while [ -n "$root" ]; do
    if [ -e "${root}/.nvimenv-version" ]; then
      echo "${root}/.nvimenv-version"
      exit
    elif [ -e "${root}/.nvimenv-version" ]; then
      echo "${root}/.nvimenv-version"
      exit
    fi
    root="${root%/*}"
  done
}

find_local_version_file "$NVIMENV_DIR"
[ "$NVIMENV_DIR" = "$PWD" ] || find_local_version_file "$PWD"

global_version_file="${NVIMENV_ROOT}/version"

if [ -e "$global_version_file" ]; then
  echo "$global_version_file"
elif [ -e "${NVIMENV_ROOT}/global" ]; then
  echo "${NVIMENV_ROOT}/global"
elif [ -e "${NVIMENV_ROOT}/default" ]; then
  echo "${NVIMENV_ROOT}/default"
else
  echo "$global_version_file"
fi
