#!/usr/bin/env bash
# Summary: Show the current nvim version and its origin
#
# Shows the currently selected nvim version and how it was
# selected. To obtain only the version string, use `nvimenv
# version-name'.

set -e
[ -n "$NVIMENV_DEBUG" ] && set -x

echo "$(nvimenv-version-name) (set by $(nvimenv-version-origin))"
