#!/usr/bin/env bash
set -e
[ -n "$NVIMENV_DEBUG" ] && set -x

# Provide nvimenv completions
if [ "$1" = "--complete" ]; then
  exec nvimenv-rehash --complete
fi

# When nvimenv shell integration is enabled, delegate to nvimenv-rehash,
# then tell the shell to empty its command lookup cache.
nvimenv-rehash
echo "hash -r 2>/dev/null || true"
