#!/usr/bin/env bash
# Summary: List existing nvimenv shims
# Usage: nvimenv shims [--short]

set -e
[ -n "$NVIMENV_DEBUG" ] && set -x

# Provide nvimenv completions
if [ "$1" = "--complete" ]; then
  echo --short
  exit
fi

shopt -s nullglob

for command in "${NVIMENV_ROOT}/shims/"*; do
  if [ "$1" = "--short" ]; then
    echo "${command##*/}"
  else
    echo "$command"
  fi
done | sort
